# Generated by Django 3.1.1 on 2021-05-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dali_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
